[build-system]
requires = [
    "setuptools>=68.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "featurecharacterization2d"
version = "1.1.0"
requires-python = ">=3.11"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    'numpy>=2.0.0',
    'scipy>=1.13.0',
    'matplotlib>=3.9.0',
]

[project.optional-dependencies]
extra = [
    'notebook>=7.1.1',
]

[tool.setuptools.packages.find]
exclude = ["tests*"]