% Builds the standalone GUI and its installer (MATLAB Compiler required).
% Run from any folder:
%   matlab -batch "run('matlab/GUI/build_gui.m')"
% Output:
%   matlab/GUI/GUI_installer.exe - web installer, downloads the MATLAB
%                                   Runtime of the MATLAB release used here
version = "1.2.0";

gui = fileparts(mfilename('fullpath'));
root = fileparts(gui);
toolbox = fullfile(root, 'featurecharacterization2d');
softgauge = fullfile(root, 'softgauge');
addpath(toolbox, softgauge);
build = fullfile(tempdir, 'FC_build');
if exist(build, 'dir')
    rmdir(build, 's');
end

%% standalone application
opts = compiler.build.StandaloneApplicationOptions(fullfile(gui, 'GUI.m'), ...
    'ExecutableName', 'FC', ...
    'ExecutableVersion', version, ...
    'ExecutableIcon', fullfile(gui, 'resources', 'icon_48.png'), ...
    'AdditionalFiles', {toolbox, softgauge}, ...
    'OutputDir', fullfile(build, 'app'));
results = compiler.build.standaloneApplication(opts);

%% installer (MATLAB Runtime is downloaded during installation)
compiler.package.installer(results, ...
    'ApplicationName', 'Feature Characterization', ...
    'Version', version, ...
    'InstallerName', 'GUI_installer', ...
    'InstallerIcon', fullfile(gui, 'resources', 'icon_48.png'), ...
    'RuntimeDelivery', 'web', ...
    'Summary', 'Feature characterization of profiles according to ISO 21920-2', ...
    'OutputDir', fullfile(build, 'installer'));
copyfile(fullfile(build, 'installer', 'GUI_installer.exe'), gui);
fprintf('Installer: %s\n', fullfile(gui, 'GUI_installer.exe'));
