"""
Tests for reading softgauge files (*.smd) and the named feature parameters
with default settings. Reference values are generated by
matlab/tests/generate_reference_values.m.
"""

import csv
from pathlib import Path

import numpy as np
import pytest
from scipy.io import loadmat

from featurecharacterization2d import default_fc_parameters, read_smd

TESTS = Path(__file__).resolve().parent
PROFILES = TESTS.parents[1] / "data" / "profiles"
DX = 0.5e-3  # mm


def read_reference(filename):
    with open(TESTS / "data" / filename, newline="") as f:
        return list(csv.DictReader(f))


SMD_REFERENCE = read_reference("matlab_reference_smd.csv")
DEFAULT_REFERENCE = read_reference("matlab_reference_default.csv")


# softgauge files of the case studies ---------------------------------------


@pytest.mark.parametrize("ref", SMD_REFERENCE, ids=lambda r: r["file"])
def test_read_smd_matches_matlab(ref):
    z, L, x, dx = read_smd(PROFILES / ref["file"])
    assert z.size == int(ref["n"])
    assert dx == float(ref["dx"])
    assert L == float(ref["L"])
    assert x[-1] == float(ref["x_end"])
    assert z[0] == float(ref["z_first"])
    assert z[-1] == float(ref["z_last"])
    np.testing.assert_allclose(np.sum(z), float(ref["z_sum"]), rtol=1e-12, atol=1e-9)


@pytest.mark.parametrize("ref", SMD_REFERENCE, ids=lambda r: r["file"])
def test_read_smd_matches_mat_file(ref):
    z, _, _, _ = read_smd(PROFILES / ref["file"])
    z_mat = loadmat(PROFILES / ref["file"].replace(".smd", ".mat"))["z"].reshape(-1)
    np.testing.assert_array_equal(z, z_mat)


# named feature parameters with default settings ----------------------------


@pytest.mark.parametrize(
    "ref", DEFAULT_REFERENCE, ids=lambda r: f"{r['profile']}|{r['parameter']}"
)
def test_default_fc_parameters(ref):
    z = loadmat(PROFILES / f"{ref['profile']}.mat")["z"].reshape(-1)
    xFC = default_fc_parameters(z - np.mean(z), DX)
    np.testing.assert_allclose(xFC[ref["parameter"]], float(ref["value"]), rtol=1e-9)


# synthetic softgauge files -------------------------------------------------

Z = np.array([1.0, -2.0, 3.5, 0.25, -1.5])


def write_smd(path, cx, cz, values, sep=b"\x00", checksum_offset=0):
    lines = b"".join(f"{v}\r\n".encode() for v in values)
    body = (
        b"ISO 5436 - 2000"
        + sep
        + b"test"
        + sep
        + b"\r\n"
        + b"PRF"
        + sep
        + b" 0 ISO0000"
        + sep
        + b"\r\n"
        + cx.replace(b" ", sep)
        + b"\r\n"
        + cz.replace(b" ", sep)
        + b"\r\n\x03\r\n"
        + b"DATE -"
        + sep
        + b"\r\n\x03\r\n"
        + lines
        + b"\x03\r\n"
    )
    checksum = sum(body) % 65535 + checksum_offset
    path.write_bytes(body + f"{checksum}\r\n".encode() + b"\x03\r\n\x1a")
    return path


@pytest.mark.parametrize(
    "cx, cz, values, z_expected, dx_expected",
    [
        (b"CX I 5 mm 1.0 D 5.0E-004", b"CZ A 5 um 1.0 D", Z, Z, 5e-4),
        (b"CX I 5 mm 2.0 D 5.0E-004", b"CZ A 5 um 2.0 D", Z, 2 * Z, 1e-3),
        (b"CX I 5 um 1.0 D 5.0E-001", b"CZ A 5 mm 1.0 D", Z, 1e3 * Z, 5e-4),
        (b"CX I 5 m 1.0 D 5.0E-007", b"CZ A 5 nm 1.0 D", Z, 1e-3 * Z, 5e-4),
    ],
    ids=["mm_um", "scale_factors", "um_mm", "m_nm"],
)
def test_read_smd_units_and_scale(tmp_path, cx, cz, values, z_expected, dx_expected):
    z, L, x, dx = read_smd(write_smd(tmp_path / "t.smd", cx, cz, values))
    np.testing.assert_allclose(z, z_expected, rtol=1e-15)
    np.testing.assert_allclose(dx, dx_expected, rtol=1e-15)
    np.testing.assert_allclose(L, Z.size * dx_expected, rtol=1e-15)
    np.testing.assert_allclose(x, np.arange(Z.size) * dx_expected, rtol=1e-15)


def test_read_smd_blank_separators(tmp_path):
    z, *_ = read_smd(
        write_smd(
            tmp_path / "t.smd",
            b"CX I 5 mm 1.0 D 5.0E-004",
            b"CZ A 5 um 1.0 D",
            Z,
            sep=b" ",
        )
    )
    np.testing.assert_array_equal(z, Z)


def test_read_smd_checksum_warning(tmp_path):
    path = write_smd(
        tmp_path / "t.smd",
        b"CX I 5 mm 1.0 D 5.0E-004",
        b"CZ A 5 um 1.0 D",
        Z,
        checksum_offset=1,
    )
    with pytest.warns(UserWarning, match="Checksum"):
        read_smd(path)


def test_read_smd_number_of_values_warning(tmp_path):
    path = write_smd(
        tmp_path / "t.smd", b"CX I 6 mm 1.0 D 5.0E-004", b"CZ A 6 um 1.0 D", Z
    )
    with pytest.warns(UserWarning, match="differs from the header"):
        z, *_ = read_smd(path)
    assert z.size == Z.size


def test_read_smd_invalid_value(tmp_path):
    path = write_smd(
        tmp_path / "t.smd",
        b"CX I 5 mm 1.0 D 5.0E-004",
        b"CZ A 5 um 1.0 D",
        ["1.0", "-2.0", "", "0.25", "-1.5"],
    )
    with pytest.raises(ValueError, match="line 3"):
        read_smd(path)


@pytest.mark.parametrize(
    "cx, cz, message",
    [
        (b"CX A 5 mm 1.0 D", b"CZ A 5 um 1.0 D", "incremental"),
        (b"CX I 5 mm 1.0 D 5.0E-004", b"CZ I 5 um 1.0 D 1.0", "absolute"),
        (b"CX I 5 in 1.0 D 5.0E-004", b"CZ A 5 um 1.0 D", "Unknown unit"),
    ],
    ids=["x_absolute", "z_incremental", "unit"],
)
def test_read_smd_unsupported_header(tmp_path, cx, cz, message):
    with pytest.raises(ValueError, match=message):
        read_smd(write_smd(tmp_path / "t.smd", cx, cz, Z))
