"""
Regression tests against the MATLAB implementation.

Reference values are generated by matlab/tests/generate_reference_values.m
and stored in tests/data/*.csv. Profiles are taken from data/profiles,
mean-centred, with dx = 0.5e-3 mm.
"""

import csv
import warnings
from pathlib import Path

import numpy as np
import pytest
from scipy.io import loadmat

from featurecharacterization2d import (
    feature_characterization,
    inverse_material_ratio,
    maximum_height,
)

TESTS = Path(__file__).resolve().parent
PROFILES = TESTS.parents[1] / "data" / "profiles"
DX = 0.5e-3  # mm
RTOL = 1e-9


def load_profile(name):
    z = loadmat(PROFILES / f"{name}.mat")["z"].reshape(-1)
    return z - np.mean(z)


def read_reference(filename):
    with open(TESTS / "data" / filename, newline="") as f:
        return list(csv.DictReader(f))


def to_float(value):
    return float("nan") if value == "NaN" else float(value)


FC_REFERENCE = read_reference("matlab_reference_fc.csv")
RZ_RCM_REFERENCE = read_reference("matlab_reference_rz_rcm.csv")

# Known deviations from MATLAB, kept visible as expected failures
KNOWN_DEVIATIONS = {
    ("Luftpresser_1_56_ak", "Wolfprune opt"): (
        "optimal periodicity: MATLAB TH_for_optimal_periodicity stops at nM > 3, "
        "Python Watershed.optimal_periodicity at nM > 2"
    ),
}


def fc_param(ref):
    reason = KNOWN_DEVIATIONS.get((ref["profile"], ref["pruning"]))
    marks = [pytest.mark.xfail(reason=reason, strict=True)] if reason else []
    return pytest.param(
        ref,
        marks=marks,
        id=f"{ref['profile']}|{ref['FT']}|{ref['pruning']}|{ref['significant']}"
        f"|{ref['AT']}|{ref['stats']}",
    )


@pytest.mark.parametrize("ref", [fc_param(r) for r in FC_REFERENCE])
def test_feature_characterization(ref):
    z = load_profile(ref["profile"])
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        xFC, M, meta = feature_characterization(
            z, DX, ref["FT"], ref["pruning"], ref["significant"], ref["AT"],
            ref["stats"],
        )
    assert meta["nM"] == int(ref["nM"])
    np.testing.assert_allclose(xFC, to_float(ref["xFC"]), rtol=RTOL, equal_nan=True)


@pytest.mark.parametrize(
    "ref",
    [r for r in RZ_RCM_REFERENCE if r["quantity"] == "Rz"],
    ids=lambda r: r["profile"],
)
def test_maximum_height(ref):
    z = load_profile(ref["profile"])
    np.testing.assert_allclose(maximum_height(z, DX), to_float(ref["value"]), rtol=RTOL)


@pytest.mark.parametrize(
    "ref",
    # p = 0 % is excluded: MATLAB Rcm.p returns NaN, Python returns Rcm = 0
    [r for r in RZ_RCM_REFERENCE if r["quantity"] == "Rcm" and float(r["p"]) > 0],
    ids=lambda r: f"{r['profile']}|p={r['p']}",
)
def test_inverse_material_ratio(ref):
    z = load_profile(ref["profile"])
    np.testing.assert_allclose(
        inverse_material_ratio(z, float(ref["p"])), to_float(ref["value"]), rtol=RTOL
    )
